### ISSUE TITLE
Build instructions or pre-build hex-file?

### ISSUE THREAD

**Issue by molotowtales** [mitxela/synthcable#1]
Would it be possible to either provide build instructions for translating asm to hex, or like in some other of your project, provide the hex-file?

I've tried to build with `avra` (https://github.com/hsoft/avra) without much progress. :/

**Comment by mitxela** [comment]
avrasm2 is the assembler I used, the official one from atmel. It comes with AVR studio (you can download an old version if you don't want the many-gigabyte bloated current version). Or find a copy of avrasm2.exe on the web (just a few hundred kb).

There's some discussion on using it here: https://github.com/mitxela/kiloboot/issues/2

I will add a hex file at some point when I get a chance.

**Comment by molotowtales** [comment]
Thanks!

I was able to build it with `avrasm2.exe -I include/ SynthCable.asm -fI -o SynthCable.hex`. Sent a pull request with the hex-file.
